[package]
name = "raphtalia/adornee"
description = "Library for constructing adornees"
version = "1.0.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
